# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ComedySoc
description: > # this means to ignore newlines until "baseurl:"
  University of York Comedy Society
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
author: Qumarth Jash
author_website: http://qumarth.me
designer: Ed Williams
designer_website: http://twitter.com/Edface

# Build settings
markdown: kramdown

shambles_website: http://comedysoc.github.io/shambles-website
